/* XPM */
static const char *bar_graph_icon[] = {
/* columns rows colors chars-per-pixel */
"28 32 7 1 ",
"* c black",
"  c None",
"r c red",
"g c #738276",
"b c blue",
"o c orange",
"p c purple",
/* pixels */
"                            ",
"                            ",
"                ******      ",
"                *pppp*      ",
"                *pppp*      ",
"                *pppp*      ",
"                *pppp*      ",
"                *pppp*      ",
"                *pppp*      ",
"      ******    *pppp*      ",
"      *oooo*    *pppp*      ",
"      *oooo******pppp*      ",
"      *oooo*gggg*pppp*      ",
"      *oooo*gggg*pppp*      ",
"      *oooo*gggg*pppp*      ",
"      *oooo*gggg*pppp*      ",
"      *oooo*gggg*pppp****** ",
"      *oooo*gggg*pppp*rrrr* ",
"      *oooo*gggg*pppp*rrrr* ",
"      *oooo*gggg*pppp*rrrr* ",
" ******oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" *bbbb*oooo*gggg*pppp*rrrr* ",
" ************************** ",
"                            ",
};
